
package de.uniluebeck.itm.pollservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PollWebService", targetNamespace = "www.itm.uniluebeck.de/pollservice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PollWebService {


    /**
     * 
     * @param languageCode
     * @return
     *     returns java.util.List<de.uniluebeck.itm.pollservice.XsPollInfo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPolls", targetNamespace = "www.itm.uniluebeck.de/pollservice", className = "de.uniluebeck.itm.pollservice.GetPolls")
    @ResponseWrapper(localName = "getPollsResponse", targetNamespace = "www.itm.uniluebeck.de/pollservice", className = "de.uniluebeck.itm.pollservice.GetPollsResponse")
    public List<XsPollInfo> getPolls(
        @WebParam(name = "languageCode", targetNamespace = "")
        String languageCode);

    /**
     * 
     * @param languageCode
     * @param pollId
     * @return
     *     returns de.uniluebeck.itm.pollservice.XsPoll
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPoll", targetNamespace = "www.itm.uniluebeck.de/pollservice", className = "de.uniluebeck.itm.pollservice.GetPoll")
    @ResponseWrapper(localName = "getPollResponse", targetNamespace = "www.itm.uniluebeck.de/pollservice", className = "de.uniluebeck.itm.pollservice.GetPollResponse")
    public XsPoll getPoll(
        @WebParam(name = "pollId", targetNamespace = "")
        String pollId,
        @WebParam(name = "languageCode", targetNamespace = "")
        String languageCode);

    /**
     * 
     * @param voteForOptions
     */
    @WebMethod
    @RequestWrapper(localName = "voteForOptions", targetNamespace = "www.itm.uniluebeck.de/pollservice", className = "de.uniluebeck.itm.pollservice.VoteForOptions")
    @ResponseWrapper(localName = "voteForOptionsResponse", targetNamespace = "www.itm.uniluebeck.de/pollservice", className = "de.uniluebeck.itm.pollservice.VoteForOptionsResponse")
    public void voteForOptions(
        @WebParam(name = "voteForOptions", targetNamespace = "")
        XsVote voteForOptions);

}
